"""add cv models: cv, work_experience, education, skill

Revision ID: 1fb7d4566967
Revises: f9bd29d36ee8
Create Date: 2025-11-27 12:34:31.971827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb7d4566967'
down_revision = 'f9bd29d36ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_id'), 'cv', ['id'], unique=False)
    op.create_index(op.f('ix_cv_user_id'), 'cv', ['user_id'], unique=False)
    op.create_table('education',
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_cv_id'), 'education', ['cv_id'], unique=False)
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_table('skill',
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_cv_id'), 'skill', ['cv_id'], unique=False)
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('workexperience',
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workexperience_cv_id'), 'workexperience', ['cv_id'], unique=False)
    op.create_index(op.f('ix_workexperience_id'), 'workexperience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workexperience_id'), table_name='workexperience')
    op.drop_index(op.f('ix_workexperience_cv_id'), table_name='workexperience')
    op.drop_table('workexperience')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_cv_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_index(op.f('ix_education_cv_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_cv_user_id'), table_name='cv')
    op.drop_index(op.f('ix_cv_id'), table_name='cv')
    op.drop_table('cv')
    # ### end Alembic commands ###
