"""enhance education model with gpa, honors, subjects, thesis

Revision ID: 25f9841d5e79
Revises: bce03a9702bf
Create Date: 2025-11-27 12:48:09.666717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f9841d5e79'
down_revision = 'bce03a9702bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('gpa', sa.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('education', sa.Column('honors', sa.String(), nullable=True))
    op.add_column('education', sa.Column('relevant_subjects', sa.Text(), nullable=True))
    op.add_column('education', sa.Column('thesis_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'thesis_title')
    op.drop_column('education', 'relevant_subjects')
    op.drop_column('education', 'honors')
    op.drop_column('education', 'gpa')
    # ### end Alembic commands ###
