"""

Revision ID: 6275f7ac4957
Revises: ab8c04eca7ff
Create Date: 2025-12-13 14:17:27.739789

"""

# revision identifiers, used by Alembic.
revision = "6275f7ac4957"
down_revision = "ab8c04eca7ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
