"""

Revision ID: ab8c04eca7ff
Revises: 7c1c0c9d8a2b
Create Date: 2025-12-12 14:11:12.846778

"""



# revision identifiers, used by Alembic.
revision = "ab8c04eca7ff"
down_revision = "7c1c0c9d8a2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
