/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppHelpIndexRouteImport } from './routes/app/help/index'
import { Route as AppCvsIndexRouteImport } from './routes/app/cvs/index'
import { Route as AppHelpGettingStartedRouteImport } from './routes/app/help/getting-started'
import { Route as AppHelpFaqRouteImport } from './routes/app/help/faq'
import { Route as AppCvsNewRouteImport } from './routes/app/cvs/new'
import { Route as AppAccountSecurityRouteImport } from './routes/app/account/security'
import { Route as AppAccountProfileRouteImport } from './routes/app/account/profile'
import { Route as AppCvsIdPreviewRouteImport } from './routes/app/cvs/$id/preview'
import { Route as AppCvsIdExportRouteImport } from './routes/app/cvs/$id/export'
import { Route as AppCvsIdEditRouteImport } from './routes/app/cvs/$id/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpIndexRoute = AppHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsIndexRoute = AppCvsIndexRouteImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpGettingStartedRoute = AppHelpGettingStartedRouteImport.update({
  id: '/help/getting-started',
  path: '/help/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpFaqRoute = AppHelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsNewRoute = AppCvsNewRouteImport.update({
  id: '/cvs/new',
  path: '/cvs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsIdPreviewRoute = AppCvsIdPreviewRouteImport.update({
  id: '/cvs/$id/preview',
  path: '/cvs/$id/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsIdExportRoute = AppCvsIdExportRouteImport.update({
  id: '/cvs/$id/export',
  path: '/cvs/$id/export',
  getParentRoute: () => AppRoute,
} as any)
const AppCvsIdEditRoute = AppCvsIdEditRouteImport.update({
  id: '/cvs/$id/edit',
  path: '/cvs/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/help/faq': typeof AppHelpFaqRoute
  '/app/help/getting-started': typeof AppHelpGettingStartedRoute
  '/app/cvs': typeof AppCvsIndexRoute
  '/app/help': typeof AppHelpIndexRoute
  '/app/cvs/$id/edit': typeof AppCvsIdEditRoute
  '/app/cvs/$id/export': typeof AppCvsIdExportRoute
  '/app/cvs/$id/preview': typeof AppCvsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/help/faq': typeof AppHelpFaqRoute
  '/app/help/getting-started': typeof AppHelpGettingStartedRoute
  '/app/cvs': typeof AppCvsIndexRoute
  '/app/help': typeof AppHelpIndexRoute
  '/app/cvs/$id/edit': typeof AppCvsIdEditRoute
  '/app/cvs/$id/export': typeof AppCvsIdExportRoute
  '/app/cvs/$id/preview': typeof AppCvsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/help/faq': typeof AppHelpFaqRoute
  '/app/help/getting-started': typeof AppHelpGettingStartedRoute
  '/app/cvs/': typeof AppCvsIndexRoute
  '/app/help/': typeof AppHelpIndexRoute
  '/app/cvs/$id/edit': typeof AppCvsIdEditRoute
  '/app/cvs/$id/export': typeof AppCvsIdExportRoute
  '/app/cvs/$id/preview': typeof AppCvsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/cvs/new'
    | '/app/help/faq'
    | '/app/help/getting-started'
    | '/app/cvs'
    | '/app/help'
    | '/app/cvs/$id/edit'
    | '/app/cvs/$id/export'
    | '/app/cvs/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/cvs/new'
    | '/app/help/faq'
    | '/app/help/getting-started'
    | '/app/cvs'
    | '/app/help'
    | '/app/cvs/$id/edit'
    | '/app/cvs/$id/export'
    | '/app/cvs/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/cvs/new'
    | '/app/help/faq'
    | '/app/help/getting-started'
    | '/app/cvs/'
    | '/app/help/'
    | '/app/cvs/$id/edit'
    | '/app/cvs/$id/export'
    | '/app/cvs/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help/': {
      id: '/app/help/'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cvs/': {
      id: '/app/cvs/'
      path: '/cvs'
      fullPath: '/app/cvs'
      preLoaderRoute: typeof AppCvsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help/getting-started': {
      id: '/app/help/getting-started'
      path: '/help/getting-started'
      fullPath: '/app/help/getting-started'
      preLoaderRoute: typeof AppHelpGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help/faq': {
      id: '/app/help/faq'
      path: '/help/faq'
      fullPath: '/app/help/faq'
      preLoaderRoute: typeof AppHelpFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cvs/new': {
      id: '/app/cvs/new'
      path: '/cvs/new'
      fullPath: '/app/cvs/new'
      preLoaderRoute: typeof AppCvsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/security': {
      id: '/app/account/security'
      path: '/account/security'
      fullPath: '/app/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/profile': {
      id: '/app/account/profile'
      path: '/account/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cvs/$id/preview': {
      id: '/app/cvs/$id/preview'
      path: '/cvs/$id/preview'
      fullPath: '/app/cvs/$id/preview'
      preLoaderRoute: typeof AppCvsIdPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cvs/$id/export': {
      id: '/app/cvs/$id/export'
      path: '/cvs/$id/export'
      fullPath: '/app/cvs/$id/export'
      preLoaderRoute: typeof AppCvsIdExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cvs/$id/edit': {
      id: '/app/cvs/$id/edit'
      path: '/cvs/$id/edit'
      fullPath: '/app/cvs/$id/edit'
      preLoaderRoute: typeof AppCvsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppCvsNewRoute: typeof AppCvsNewRoute
  AppHelpFaqRoute: typeof AppHelpFaqRoute
  AppHelpGettingStartedRoute: typeof AppHelpGettingStartedRoute
  AppCvsIndexRoute: typeof AppCvsIndexRoute
  AppHelpIndexRoute: typeof AppHelpIndexRoute
  AppCvsIdEditRoute: typeof AppCvsIdEditRoute
  AppCvsIdExportRoute: typeof AppCvsIdExportRoute
  AppCvsIdPreviewRoute: typeof AppCvsIdPreviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppCvsNewRoute: AppCvsNewRoute,
  AppHelpFaqRoute: AppHelpFaqRoute,
  AppHelpGettingStartedRoute: AppHelpGettingStartedRoute,
  AppCvsIndexRoute: AppCvsIndexRoute,
  AppHelpIndexRoute: AppHelpIndexRoute,
  AppCvsIdEditRoute: AppCvsIdEditRoute,
  AppCvsIdExportRoute: AppCvsIdExportRoute,
  AppCvsIdPreviewRoute: AppCvsIdPreviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
